# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'editingdevicedialog.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_EditingDevDialog(object):
    def setupUi(self, EditingDevDialog):
        EditingDevDialog.setObjectName("EditingDevDialog")
        EditingDevDialog.resize(663, 416)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(EditingDevDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tipsLabel = QtWidgets.QLabel(EditingDevDialog)
        self.tipsLabel.setObjectName("tipsLabel")
        self.verticalLayout_2.addWidget(self.tipsLabel)
        self.line = QtWidgets.QFrame(EditingDevDialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(EditingDevDialog)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.selectedListWidget = QtWidgets.QListWidget(self.frame)
        self.selectedListWidget.setObjectName("selectedListWidget")
        self.verticalLayout_3.addWidget(self.selectedListWidget)
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.devGroupBox = QtWidgets.QGroupBox(self.frame)
        self.devGroupBox.setObjectName("devGroupBox")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.devGroupBox)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.devGroupBox)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.posSpinBox = QtWidgets.QSpinBox(self.devGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.posSpinBox.sizePolicy().hasHeightForWidth())
        self.posSpinBox.setSizePolicy(sizePolicy)
        self.posSpinBox.setObjectName("posSpinBox")
        self.horizontalLayout_3.addWidget(self.posSpinBox)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_2 = QtWidgets.QLabel(self.devGroupBox)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_4.addWidget(self.label_2)
        self.speedSpinBox = QtWidgets.QSpinBox(self.devGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.speedSpinBox.sizePolicy().hasHeightForWidth())
        self.speedSpinBox.setSizePolicy(sizePolicy)
        self.speedSpinBox.setObjectName("speedSpinBox")
        self.horizontalLayout_4.addWidget(self.speedSpinBox)
        self.verticalLayout_5.addLayout(self.horizontalLayout_4)
        self.verticalLayout_3.addWidget(self.devGroupBox)
        self.horizontalLayout_2.addWidget(self.frame)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.rmPushButton = QtWidgets.QPushButton(EditingDevDialog)
        self.rmPushButton.setAutoDefault(False)
        self.rmPushButton.setObjectName("rmPushButton")
        self.verticalLayout.addWidget(self.rmPushButton)
        self.addPushButton = QtWidgets.QPushButton(EditingDevDialog)
        self.addPushButton.setAutoDefault(False)
        self.addPushButton.setObjectName("addPushButton")
        self.verticalLayout.addWidget(self.addPushButton)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.frame_2 = QtWidgets.QFrame(EditingDevDialog)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.optionListWidget = QtWidgets.QListWidget(self.frame_2)
        self.optionListWidget.setObjectName("optionListWidget")
        self.verticalLayout_4.addWidget(self.optionListWidget)
        self.horizontalLayout_2.addWidget(self.frame_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.applyPushButton = QtWidgets.QPushButton(EditingDevDialog)
        self.applyPushButton.setAutoDefault(False)
        self.applyPushButton.setObjectName("applyPushButton")
        self.horizontalLayout.addWidget(self.applyPushButton)
        self.cancelPushButton = QtWidgets.QPushButton(EditingDevDialog)
        self.cancelPushButton.setAutoDefault(True)
        self.cancelPushButton.setObjectName("cancelPushButton")
        self.horizontalLayout.addWidget(self.cancelPushButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(EditingDevDialog)
        QtCore.QMetaObject.connectSlotsByName(EditingDevDialog)

    def retranslateUi(self, EditingDevDialog):
        _translate = QtCore.QCoreApplication.translate
        EditingDevDialog.setWindowTitle(_translate("EditingDevDialog", "Dialog"))
        self.tipsLabel.setText(_translate("EditingDevDialog", "请使用“<<<”添加设备， “>>>” 删除设备，选择完成后点击应用"))
        self.label_3.setText(_translate("EditingDevDialog", "已选设备:"))
        self.label_5.setText(_translate("EditingDevDialog", "调整设备信息:"))
        self.devGroupBox.setTitle(_translate("EditingDevDialog", "设备"))
        self.label.setText(_translate("EditingDevDialog", "位置："))
        self.label_2.setText(_translate("EditingDevDialog", "速度："))
        self.rmPushButton.setText(_translate("EditingDevDialog", ">>>"))
        self.addPushButton.setText(_translate("EditingDevDialog", "<<<"))
        self.label_4.setText(_translate("EditingDevDialog", "可选设备"))
        self.applyPushButton.setText(_translate("EditingDevDialog", "应用"))
        self.cancelPushButton.setText(_translate("EditingDevDialog", "取消"))

