# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(804, 609)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.titleFrame = QtWidgets.QFrame(Form)
        self.titleFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.titleFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.titleFrame.setObjectName("titleFrame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.titleFrame)
        self.horizontalLayout_4.setContentsMargins(150, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(10)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.versionLabel = QtWidgets.QLabel(self.titleFrame)
        self.versionLabel.setObjectName("versionLabel")
        self.horizontalLayout_4.addWidget(self.versionLabel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem)
        self.databaseLabel = QtWidgets.QLabel(self.titleFrame)
        self.databaseLabel.setObjectName("databaseLabel")
        self.horizontalLayout_4.addWidget(self.databaseLabel)
        self.internetLabel = QtWidgets.QLabel(self.titleFrame)
        self.internetLabel.setObjectName("internetLabel")
        self.horizontalLayout_4.addWidget(self.internetLabel)
        self.plcStateLabel = QtWidgets.QLabel(self.titleFrame)
        self.plcStateLabel.setObjectName("plcStateLabel")
        self.horizontalLayout_4.addWidget(self.plcStateLabel)
        self.timeLabel = QtWidgets.QLabel(self.titleFrame)
        self.timeLabel.setObjectName("timeLabel")
        self.horizontalLayout_4.addWidget(self.timeLabel)
        self.verticalLayout_2.addWidget(self.titleFrame)
        self.frame_3 = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.emptyFrame = QtWidgets.QFrame(self.frame_3)
        self.emptyFrame.setMinimumSize(QtCore.QSize(0, 0))
        self.emptyFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.emptyFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.emptyFrame.setObjectName("emptyFrame")
        self.horizontalLayout_5.addWidget(self.emptyFrame)
        self.contentFrame = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.contentFrame.sizePolicy().hasHeightForWidth())
        self.contentFrame.setSizePolicy(sizePolicy)
        self.contentFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contentFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contentFrame.setObjectName("contentFrame")
        self.horizontalLayout_5.addWidget(self.contentFrame)
        self.selectWidgetFrame = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.selectWidgetFrame.sizePolicy().hasHeightForWidth())
        self.selectWidgetFrame.setSizePolicy(sizePolicy)
        self.selectWidgetFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.selectWidgetFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.selectWidgetFrame.setObjectName("selectWidgetFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.selectWidgetFrame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.displayMethodLabel = QtWidgets.QLabel(self.selectWidgetFrame)
        self.displayMethodLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.displayMethodLabel.setObjectName("displayMethodLabel")
        self.verticalLayout.addWidget(self.displayMethodLabel)
        self.dataShowingPushButton = QtWidgets.QPushButton(self.selectWidgetFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dataShowingPushButton.sizePolicy().hasHeightForWidth())
        self.dataShowingPushButton.setSizePolicy(sizePolicy)
        self.dataShowingPushButton.setMinimumSize(QtCore.QSize(50, 50))
        self.dataShowingPushButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.dataShowingPushButton.setObjectName("dataShowingPushButton")
        self.verticalLayout.addWidget(self.dataShowingPushButton)
        self.graphicShowingPushButton = QtWidgets.QPushButton(self.selectWidgetFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicShowingPushButton.sizePolicy().hasHeightForWidth())
        self.graphicShowingPushButton.setSizePolicy(sizePolicy)
        self.graphicShowingPushButton.setMinimumSize(QtCore.QSize(50, 50))
        self.graphicShowingPushButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.graphicShowingPushButton.setObjectName("graphicShowingPushButton")
        self.verticalLayout.addWidget(self.graphicShowingPushButton)
        self.autoRunningPushButton = QtWidgets.QPushButton(self.selectWidgetFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.autoRunningPushButton.sizePolicy().hasHeightForWidth())
        self.autoRunningPushButton.setSizePolicy(sizePolicy)
        self.autoRunningPushButton.setMinimumSize(QtCore.QSize(50, 50))
        self.autoRunningPushButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.autoRunningPushButton.setCheckable(True)
        self.autoRunningPushButton.setObjectName("autoRunningPushButton")
        self.verticalLayout.addWidget(self.autoRunningPushButton)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_5.addWidget(self.selectWidgetFrame)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.ctrlFrame = QtWidgets.QFrame(Form)
        self.ctrlFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.ctrlFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.ctrlFrame.setObjectName("ctrlFrame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.ctrlFrame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.modalTextLabel = QtWidgets.QLabel(self.ctrlFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modalTextLabel.sizePolicy().hasHeightForWidth())
        self.modalTextLabel.setSizePolicy(sizePolicy)
        self.modalTextLabel.setMinimumSize(QtCore.QSize(0, 0))
        self.modalTextLabel.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.modalTextLabel.setObjectName("modalTextLabel")
        self.horizontalLayout_3.addWidget(self.modalTextLabel)
        self.frame_2 = QtWidgets.QFrame(self.ctrlFrame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.organizedPlayPushButton = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.organizedPlayPushButton.sizePolicy().hasHeightForWidth())
        self.organizedPlayPushButton.setSizePolicy(sizePolicy)
        self.organizedPlayPushButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.organizedPlayPushButton.setObjectName("organizedPlayPushButton")
        self.horizontalLayout_2.addWidget(self.organizedPlayPushButton)
        self.netFramePushButton = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.netFramePushButton.sizePolicy().hasHeightForWidth())
        self.netFramePushButton.setSizePolicy(sizePolicy)
        self.netFramePushButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.netFramePushButton.setObjectName("netFramePushButton")
        self.horizontalLayout_2.addWidget(self.netFramePushButton)
        self.systemManagementPushButton = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.systemManagementPushButton.sizePolicy().hasHeightForWidth())
        self.systemManagementPushButton.setSizePolicy(sizePolicy)
        self.systemManagementPushButton.setMinimumSize(QtCore.QSize(0, 0))
        self.systemManagementPushButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.systemManagementPushButton.setObjectName("systemManagementPushButton")
        self.horizontalLayout_2.addWidget(self.systemManagementPushButton)
        self.helpPushButton = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.helpPushButton.sizePolicy().hasHeightForWidth())
        self.helpPushButton.setSizePolicy(sizePolicy)
        self.helpPushButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.helpPushButton.setObjectName("helpPushButton")
        self.horizontalLayout_2.addWidget(self.helpPushButton)
        self.exitPushButton = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exitPushButton.sizePolicy().hasHeightForWidth())
        self.exitPushButton.setSizePolicy(sizePolicy)
        self.exitPushButton.setFocusPolicy(QtCore.Qt.NoFocus)
        self.exitPushButton.setObjectName("exitPushButton")
        self.horizontalLayout_2.addWidget(self.exitPushButton)
        self.horizontalLayout_3.addWidget(self.frame_2)
        self.horizontalLayout.addWidget(self.ctrlFrame)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem3)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        self.exitPushButton.clicked.connect(Form.close)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.versionLabel.setText(_translate("Form", "系统版本"))
        self.databaseLabel.setText(_translate("Form", "数据库"))
        self.internetLabel.setText(_translate("Form", "网络连接状态"))
        self.plcStateLabel.setText(_translate("Form", "PLC控制器版本"))
        self.timeLabel.setText(_translate("Form", "时间"))
        self.displayMethodLabel.setText(_translate("Form", "显示模式"))
        self.dataShowingPushButton.setText(_translate("Form", "数据显示"))
        self.graphicShowingPushButton.setText(_translate("Form", "图形显示"))
        self.autoRunningPushButton.setText(_translate("Form", "场景运行"))
        self.modalTextLabel.setText(_translate("Form", "运行模式"))
        self.organizedPlayPushButton.setText(_translate("Form", "编场"))
        self.netFramePushButton.setText(_translate("Form", "设备网络图"))
        self.systemManagementPushButton.setText(_translate("Form", "系统管理"))
        self.helpPushButton.setText(_translate("Form", "帮助"))
        self.exitPushButton.setText(_translate("Form", "退出"))

