# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(588, 501)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_2.addWidget(self.label_8)
        self.frame_3 = QtWidgets.QFrame(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.dataShowingPushButton = QtWidgets.QPushButton(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dataShowingPushButton.sizePolicy().hasHeightForWidth())
        self.dataShowingPushButton.setSizePolicy(sizePolicy)
        self.dataShowingPushButton.setMinimumSize(QtCore.QSize(50, 50))
        self.dataShowingPushButton.setObjectName("dataShowingPushButton")
        self.verticalLayout.addWidget(self.dataShowingPushButton)
        self.graphicShowingPushButton = QtWidgets.QPushButton(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.graphicShowingPushButton.sizePolicy().hasHeightForWidth())
        self.graphicShowingPushButton.setSizePolicy(sizePolicy)
        self.graphicShowingPushButton.setMinimumSize(QtCore.QSize(50, 50))
        self.graphicShowingPushButton.setObjectName("graphicShowingPushButton")
        self.verticalLayout.addWidget(self.graphicShowingPushButton)
        self.autoRunningPushButton = QtWidgets.QPushButton(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.autoRunningPushButton.sizePolicy().hasHeightForWidth())
        self.autoRunningPushButton.setSizePolicy(sizePolicy)
        self.autoRunningPushButton.setMinimumSize(QtCore.QSize(50, 50))
        self.autoRunningPushButton.setObjectName("autoRunningPushButton")
        self.verticalLayout.addWidget(self.autoRunningPushButton)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_5.addWidget(self.frame_5)
        self.contentFrame = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.contentFrame.sizePolicy().hasHeightForWidth())
        self.contentFrame.setSizePolicy(sizePolicy)
        self.contentFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contentFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contentFrame.setObjectName("contentFrame")
        self.horizontalLayout_5.addWidget(self.contentFrame)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setFrameShape(QtWidgets.QFrame.Box)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.modalLabel = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.modalLabel.sizePolicy().hasHeightForWidth())
        self.modalLabel.setSizePolicy(sizePolicy)
        self.modalLabel.setMinimumSize(QtCore.QSize(60, 80))
        self.modalLabel.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.modalLabel.setObjectName("modalLabel")
        self.horizontalLayout_3.addWidget(self.modalLabel)
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.arrangeFieldPushButton = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.arrangeFieldPushButton.sizePolicy().hasHeightForWidth())
        self.arrangeFieldPushButton.setSizePolicy(sizePolicy)
        self.arrangeFieldPushButton.setObjectName("arrangeFieldPushButton")
        self.horizontalLayout_2.addWidget(self.arrangeFieldPushButton)
        self.netFramePushButton = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.netFramePushButton.sizePolicy().hasHeightForWidth())
        self.netFramePushButton.setSizePolicy(sizePolicy)
        self.netFramePushButton.setObjectName("netFramePushButton")
        self.horizontalLayout_2.addWidget(self.netFramePushButton)
        self.systemManagementPushButton = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.systemManagementPushButton.sizePolicy().hasHeightForWidth())
        self.systemManagementPushButton.setSizePolicy(sizePolicy)
        self.systemManagementPushButton.setMinimumSize(QtCore.QSize(0, 0))
        self.systemManagementPushButton.setObjectName("systemManagementPushButton")
        self.horizontalLayout_2.addWidget(self.systemManagementPushButton)
        self.recordPushButton = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.recordPushButton.sizePolicy().hasHeightForWidth())
        self.recordPushButton.setSizePolicy(sizePolicy)
        self.recordPushButton.setObjectName("recordPushButton")
        self.horizontalLayout_2.addWidget(self.recordPushButton)
        self.helpPushButton = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.helpPushButton.sizePolicy().hasHeightForWidth())
        self.helpPushButton.setSizePolicy(sizePolicy)
        self.helpPushButton.setObjectName("helpPushButton")
        self.horizontalLayout_2.addWidget(self.helpPushButton)
        self.exitPushButton = QtWidgets.QPushButton(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exitPushButton.sizePolicy().hasHeightForWidth())
        self.exitPushButton.setSizePolicy(sizePolicy)
        self.exitPushButton.setObjectName("exitPushButton")
        self.horizontalLayout_2.addWidget(self.exitPushButton)
        self.horizontalLayout_3.addWidget(self.frame_2)
        self.verticalLayout_2.addWidget(self.frame)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(20)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.versionLabel = QtWidgets.QLabel(Form)
        self.versionLabel.setObjectName("versionLabel")
        self.horizontalLayout.addWidget(self.versionLabel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.internetLabel = QtWidgets.QLabel(Form)
        self.internetLabel.setObjectName("internetLabel")
        self.horizontalLayout.addWidget(self.internetLabel)
        self.plcStateLabel = QtWidgets.QLabel(Form)
        self.plcStateLabel.setObjectName("plcStateLabel")
        self.horizontalLayout.addWidget(self.plcStateLabel)
        self.timeLabel = QtWidgets.QLabel(Form)
        self.timeLabel.setObjectName("timeLabel")
        self.horizontalLayout.addWidget(self.timeLabel)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(Form)
        self.exitPushButton.clicked.connect(Form.close)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_8.setText(_translate("Form", "江苏时代演艺设备有限公司"))
        self.dataShowingPushButton.setText(_translate("Form", "数据显示"))
        self.graphicShowingPushButton.setText(_translate("Form", "图形显示"))
        self.autoRunningPushButton.setText(_translate("Form", "场景运行"))
        self.modalLabel.setText(_translate("Form", "运行模式"))
        self.arrangeFieldPushButton.setText(_translate("Form", "编场"))
        self.netFramePushButton.setText(_translate("Form", "设备网络图"))
        self.systemManagementPushButton.setText(_translate("Form", "系统管理"))
        self.recordPushButton.setText(_translate("Form", "记录"))
        self.helpPushButton.setText(_translate("Form", "帮助"))
        self.exitPushButton.setText(_translate("Form", "退出"))
        self.versionLabel.setText(_translate("Form", "系统版本"))
        self.internetLabel.setText(_translate("Form", "网络连接状态"))
        self.plcStateLabel.setText(_translate("Form", "Plc控制器版本"))
        self.timeLabel.setText(_translate("Form", "时间"))

